language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
before_script:
  - composer self-update
  - composer update
script:
  - "./vendor/bin/phpcf -t ${TRAVIS_PHP_VERSION} getWetterWarnung.php config.sample.php ./botLib"
  - "./vendor/bin/phpcpd --no-interaction getWetterWarnung.php config.sample.php ./botLib"
  - "./vendor/bin/phpcs --colors --standard=PSR1 --extensions=php getWetterWarnung.php config.sample.php botLib/*"
cache:
  directories:
    - $HOME/.composer/cache/files
